controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_to_cart:
    path: '/add-To-Cart/{basketId}'
    controller: 'App\Controller\PanierController::addToCart'

supp_element_panier:
    path: '/supp-Element-Panier/{id}'
    controller: 'App\Controller\PanierController::suppElementPanier'
supp:
    path: '/{id}/supp'
    controller: 'App\Controller\PanierController::delete'

baskett:
    path: '/baskett/{id}'
    controller: 'App\Controller\PanierController::addToCart'
