controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

filter_by_tailles:
    path: /filter-by-tailles
    controller: 'App\Controller\baskets::filterByTailles'
    methods: ['POST']